In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
import warnings

In [24]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV

In [29]:
df = pd.read_csv('data/Depression_dataset.csv')

In [30]:
df.head()

Q3A  Q5A  Q10A  Q13A  Q16A  Q17A  Q24A  Q26A  Q31A  Q42A  ...  \
0    1    3     0     3     3     2     3     3     3     3  ...   
1    1    3     1     3     2     3     1     2     1     1  ...   
2    3    3     3     3     3     3     3     0     3     3  ...   
3    1    2     2     0     1     2     0     1     2     1  ...   
4    2    3     2     3     2     3     1     3     2     2  ...   

   Reserved-quiet  Disorganized-careless  Calm-emotionally_stable  religion  \
0               7                      5                        1        12   
1               4                      7                        1         7   
2               6                      5                        3         4   
3               4                      1                        6         4   
4               5                      6                        3        10   

   Conventional-uncreative  education  orientation  married  age_group  \
0                        1          2            1        1          0   
1                        5          2            3        1          0   
2                        2          2            3        1          0   
3                        1          1            5        1          0   
4                        3          3            1        1          0   

          Condition  
0            Severe  
1            Severe  
2  Extremely Severe  
3          Moderate  
4  Extremely Severe  

[5 rows x 25 columns]

In [31]:
df.drop(columns=['religion'],axis=1,inplace=True)

In [32]:
df.columns

Index(['Q3A', 'Q5A', 'Q10A', 'Q13A', 'Q16A', 'Q17A', 'Q24A', 'Q26A', 'Q31A',
       'Q42A', 'Extraverted-enthusiastic', 'Critical-quarrelsome',
       'Dependable-self_disciplined', 'Anxious-easily upset',
       'Open to new experiences-complex', 'Reserved-quiet',
       'Disorganized-careless', 'Calm-emotionally_stable',
       'Conventional-uncreative', 'education', 'orientation', 'married',
       'age_group', 'Condition'],
      dtype='object')

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [33]:
X = df.drop(columns=['Condition'],axis=1)

In [34]:
y=df['Condition']

In [35]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((27321, 23), (6831, 23))

In [41]:
def evaluate_model(true, predicted):
    accuracy = accuracy_score(true, predicted)
    precision = precision_score(true, predicted, average='weighted')
    recall = recall_score(true, predicted, average='weighted')
    f1 = f1_score(true, predicted, average='weighted')
    confusion_mat = confusion_matrix(true, predicted)
    return accuracy, precision, recall, f1, confusion_mat

In [46]:
classifiers = {
    "KNeighborsClassifier": KNeighborsClassifier(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "AdaBoostClassifier": AdaBoostClassifier(),
    "SVC": SVC(),
    "LogisticRegression": LogisticRegression(),
}

results = {}
model_list = []
accuracy_list = []
for name, model in classifiers.items():
    model.fit(X_train, y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    train_accuracy, train_precision, train_recall, train_f1, train_confusion_mat = evaluate_model(y_train, y_train_pred)
    test_accuracy, test_precision, test_recall, test_f1, test_confusion_mat = evaluate_model(y_test, y_test_pred)
    
    model_list.append(name)
    accuracy_list.append(test_accuracy)

    print(name)
    print('Model performance for Training set:')
    print("- Accuracy: {:.4f}".format(train_accuracy))
    print("- Precision: {:.4f}".format(train_precision))
    print("- Recall: {:.4f}".format(train_recall))
    print("- F1 Score: {:.4f}".format(train_f1))
    print("- Confusion Matrix:\n", train_confusion_mat)
    print('----------------------------------')
    print('Model performance for Test set:')
    print("- Accuracy: {:.4f}".format(test_accuracy))
    print("- Precision: {:.4f}".format(test_precision))
    print("- Recall: {:.4f}".format(test_recall))
    print("- F1 Score: {:.4f}".format(test_f1))
    print("- Confusion Matrix:\n", test_confusion_mat)
    print('='*35)
    print('\n')
    
    results[name] = {
        "Train Accuracy": train_accuracy,
        "Train Precision": train_precision,
        "Train Recall": train_recall,
        "Train F1 Score": train_f1,
        "Test Accuracy": test_accuracy,
        "Test Precision": test_precision,
        "Test Recall": test_recall,
        "Test F1 Score": test_f1
    }



c:\Backend\venv\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
c:\Backend\venv\lib\site-packages\sklearn\neighbors\_classification.py:211: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or Fals

KNeighborsClassifier
Model performance for Training set:
- Accuracy: 0.8273
- Precision: 0.8275
- Recall: 0.8273
- F1 Score: 0.8238
- Confusion Matrix:
 [[8398    0   21    0  252]
 [   1 1659  597  476    5]
 [  61  586 4038   92  334]
 [   0  337  147 5774    0]
 [ 774   62  965    7 2735]]
----------------------------------
Model performance for Test set:
- Accuracy: 0.7214
- Precision: 0.7209
- Recall: 0.7214
- F1 Score: 0.7149
- Confusion Matrix:
 [[2023    0   12    0  137]
 [   0  267  233  150    6]
 [  15  254  776   43  126]
 [   0  154   52 1388    0]
 [ 321   23  375    2  474]]


DecisionTreeClassifier
Model performance for Training set:
- Accuracy: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- F1 Score: 1.0000
- Confusion Matrix:
 [[8671    0    0    0    0]
 [   0 2738    0    0    0]
 [   0    0 5111    0    0]
 [   0    0    0 6258    0]
 [   0    0    0    0 4543]]
----------------------------------
Model performance for Test set:
- Accuracy: 0.7491
- Precision: 0.752

c:\Backend\venv\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression
Model performance for Training set:
- Accuracy: 0.8109
- Precision: 0.8076
- Recall: 0.8109
- F1 Score: 0.8086
- Confusion Matrix:
 [[8097    0    4    0  570]
 [   0 1444  775  513    6]
 [  13  491 3819   30  758]
 [   0  403   43 5812    0]
 [ 723    4  833    0 2983]]
----------------------------------
Model performance for Test set:
- Accuracy: 0.8151
- Precision: 0.8127
- Recall: 0.8151
- F1 Score: 0.8124
- Confusion Matrix:
 [[2036    0    1    0  135]
 [   0  342  200  112    2]
 [   3  129  929    7  146]
 [   0   86    9 1499    0]
 [ 187    1  245    0  762]]




In [48]:
data = list(zip(model_list, accuracy_list))

# Create DataFrame
accuracy_df = pd.DataFrame(data, columns=['Model Name', 'Accuracy'])

# Sort DataFrame by Accuracy in descending order
accuracy_df_sorted = accuracy_df.sort_values(by="Accuracy", ascending=False)

In [49]:
accuracy_df_sorted

Model Name  Accuracy
4                     SVC  0.864149
3      AdaBoostClassifier  0.848338
2  RandomForestClassifier  0.844971
5      LogisticRegression  0.815108
1  DecisionTreeClassifier  0.749085
0    KNeighborsClassifier  0.721417

In [52]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf','linear']}

# Create the GridSearchCV object
grid_search = RandomizedSearchCV(SVC(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)


Best Parameters: {'kernel': 'linear', 'gamma': 0.0001, 'C': 10}
Best Score: 0.857874575195005


In [53]:
from sklearn.metrics import accuracy_score

# Get the best SVC model from the grid search
best_svc = grid_search.best_estimator_

# Predict labels on the test set
y_test_pred = best_svc.predict(X_test)

# Calculate accuracy score on the test set
test_accuracy = accuracy_score(y_test, y_test_pred)

print("Test Accuracy:", test_accuracy)


Test Accuracy: 0.8647342995169082


In [57]:
import pickle

# Save the trained model to a file
with open('sce/model.pkl', 'wb') as file:
    pickle.dump(best_svc, file)


FileNotFoundError: [Errno 2] No such file or directory: 'sce/model.pkl'

In [59]:
!pip3 install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [66]:
import os
from joblib import dump

# Create the directory if it doesn't exist
# Save the trained model to a file
dump(best_svc, 'model.joblib')


['model.joblib']